[cache]
enabled = false
[jig]
# Don't generate PCB mount so we can check model from sides
type = "component_fitting"
[holder.base]
# Solid holder to fit components in place
type = "solid_fill"
[TH]
[SMD]
# These are format conversion artifacts, best ignored
refs_do_not_process = [ 'U1', 'U3', 'CONN1', 'RPI1' ]
[TH.component_shell]
shell_clearance_from_pcb = 0.2
[SMD.component_shell]
shell_clearance_from_pcb = 0.2
